
name: CI-CD-Pipeline-to-AWS-ElasticBeanstalk
env:
  EB_PACKAGE_S3_BUCKET_NAME : "hawkincloud.flask-app"
  EB_APPLICATION_NAME       : "Hawkincloud"
  EB_ENVIRONMENT_NAME       : "Hawkincloud-env"
  DEPLOY_PACKAGE_NAME       : "hawkincloud-app-${{ github.sha }}.zip"
  AWS_REGION_NAME           : "us-east-1"

on: 
  push:
    branches: 
      - master
jobs:
    my_ci_pipeline:
       runs-on: ubuntu-latest
       
       steps:
         - name: Git clone our repository
           uses: actions/checkout@v1
            
         - name: Create ZIP deployment package
           run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./  -x  *.git*
           
         - name: Configure my AWS Credentils
           uses: aws-actions/configure-aws-credentials@v1
           with:
             aws-access-key-id    : ${{ secrets.MY_AWS_ACCESS_KEY }}
             aws-secret-access-key: ${{ secrets.MY_AWS_SECRET_KEY }}
             aws-region           : ${{ env.AWS_REGION_NAME }}

         - name: Copy our Deployment package to S3 bucket
           run : aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME}}/
         
         - name: Print nice message on completion of CI Pipeline
           run : echo "CI Pipeline part finished successfully"
           
    my_cd_pipeline:
        runs-on: ubuntu-latest
        needs : [my_ci_pipeline]
       
        steps:
          - name: Configure my AWS Credentils
            uses: aws-actions/configure-aws-credentials@v1
            with:
             aws-access-key-id    : ${{ secrets.MY_AWS_ACCESS_KEY }}
             aws-secret-access-key: ${{ secrets.MY_AWS_SECRET_KEY }}
             aws-region           : ${{ env.AWS_REGION_NAME }}
             
          - name : Create new ElasticBeanstalk Application Version
            run : |
             aws elasticbeanstalk create-application-version \
             --application-name ${{ env.EB_APPLICATION_NAME }} \
             --source-bundle S3Bucket="${{ env. EB_PACKAGE_S3_BUCKET_NAME }}",S3Key="${{ env.DEPLOY_PACKAGE_NAME }}" \
             --version-label "Ver-${{ github.sha }}" \
             --description "CommitSHA-${{ github.sha }}"
             
          - name: Deploy our new Application Version
            run: aws elasticbeanstalk update-environment --environment-name ${{ env.EB_ENVIRONMENT_NAME }} --version-label "Ver-${{ github.sha }}"
            
          - name: Print nice message on completition of CD Pipeline
            run: echo "CD Pipeline part finished successfully"
              
             
              
